BNF-1249 Bump global-nav version to match GN-166 PR (#23)
* BNF-1249 Bump global-nav version to match GN-166 PR

* BNF-1249 Apply fix to solve issue with typerror:symbol is not a function. See https://stackoverflow.com/questions/67690180/typeerror-symbol-is-not-a-function

* BNF-1249 Bump global nav version after dropdown links update

* BNF-1249 Bump global-nav version to reflect url changes

* fix merge conflict

* BNF-1249 Remove incorrect package.json entry for global-nav

* BNF-1249 Repair package.json in root

* BNF-1249 GN version bump

* BNF-1249 Bump commit GN alpha

Co-authored-by: Ian Routledge <ian@ediblecode.com>